config/routes.rb
Rails.application.routes.draw do

  root :controller => "page", :action => "index" , :locale => "fi"


  get '/en/kartta.html',   to: redirect("/en/map.html")
  get '/fi/kartta.html',   to: redirect("/fi/map.html")
  get '/de/kartta.html',   to: redirect("/de/map.html")

  scope "/:locale" do

    get "/booking.html" ,     :to => 'bookings#booking'
    post "/booking.html" ,     :to => 'bookings#booking'
    get "/confirm.html" ,     :to => 'bookings#confirm'

    get '/:page.html',
        :to => 'page#index',
        :constraints => {
          :locale => /[a-z]{2}/,
        },
        :defaults => {
          :page => "index",
          :locale => 'fi'
        }
  end
end

app/models/booking.rb
class Booking
  include ActiveModel::Model
  include ActiveModel::Validations

  attr_accessor  :email ,:arriving, :name, :comment,  :phone, :nights, :room

  validates :email , :email => true
  validates_format_of :name, :with => /\w{3,6} \w{3,6}/
  validates :phone,:presence => true,
                   :numericality => true,
                   :length => { :minimum => 8, :maximum => 15 }
  validates_presence_of :arriving
  validates :room, :presence => true
  validates_presence_of :nights

  def initialize(hash)
    super
    @arriving = Date.today + 1 unless @arriving
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :locale


  def locale
    @page =  params[:page] || "index"
    @locale = params[:locale]
    @locales = [ "en" , "fi" , "de"]
    I18n.locale = @locale
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController


  def booking
    @booking = Booking.new({})
    if request.post?
      @booking = Booking.new(params_for_model)
      puts "room is #{@booking.room}"
      if @booking.valid?
        BookingMailer.confirm(@booking).deliver
        render :confirm
        return
      else
        flash.now[:errors] = @booking.errors
      end
    end
  end

  def confirm

  end

  def params_for_model
    params.require(:booking).permit(:arriving, :nights, :email, :phone, :comment, :room ,:name)
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController

  def index
    render :template => @page
  end

end

app/helpers/application_helper.rb
module ApplicationHelper  
  
  def photos
    dir "photos"
  end
  
  def activities
    dir "activities"
  end

  def news
    dir "news"
  end
  
  def dir name
    I18n.t("#{name}.all" , :locale => :en ).split(",").collect do |n| n.strip end
  end
end

app/helpers/bookings_helper.rb
Date.class_eval do
  def to_s arg = nil
    puts "Date#{arg}"
    return strftime("%d-%m-%Y")
  end
end

module BookingsHelper

  def days
    days = (0..9).collect{ |u| start + u.days}
  end

  def start
    if(params[:start])
      start = Date.parse(params[:start])
    else
      start = Date.today
    end
  end

    def rooms
      Room.all.collect{|r| r.name }
    end

    def room_rand
      @on = rand < 0.5
    end
    def room_free(room,day)
      @on
    end
    def div(room,day)
      func = "$('#booking_room').attr('value','#{room}');"
      func += "$('#room').text('#{room}');"
      func += "$('#booking_arriving').attr('value','#{day}');"
      func += "$('#arriving').text('#{day}');"
      func = "onclick=#{func}"
      clas = room_rand ? "free" : "booked"
      div = "<div class='#{}'"
      div += func if @on
      div + ">"
    end
end

app/views/bookings/_form.html.haml
= render "matrix"
= form_for(@booking) do |f|
  - if @booking.errors.any?
    #error_explanation
      %h2
        = pluralize(@booking.errors.count, "error")
        prohibited this booking from being saved:
      %ul
        - @booking.errors.full_messages.each do |msg|
          %li= msg
  %div
    .dotted
      .field-frame
        = f.label :name
        %br/
        = f.text_field :name
      .field-frame
        = f.label :email
        %br/
        = f.text_field :email
      .field-frame
        = f.label :phone
        %br/
        = f.text_field :phone
    %div
      .field-frame
        = f.label :info
        %br/
        = f.text_field :phone
      .field-frame-2
        = f.label :days
        %br/
        = select_tag :days , options_for_select( (1..5) )
        %br/
      %div
        = hidden_field :booking , :room
        = hidden_field :booking , :arriving
      .field-frame
        %br/
        = f.submit

app/views/bookings/_matrix.html.haml
%table.book-month
  %tr
    %td{:width => "58px"}
    %td
      %a{:href => "new?start=#{start - 30.day}"} month
      = image_tag "arrow-2.gif"
    %td
      %a{:href => "new?start=#{start - 7.day}"} week
      = image_tag "arrow-2.gif"
    %td
      = start
      = image_tag "line.gif"
      = start + 10.day
      \&nbsp;&nbsp;&nbsp;
    %td
      %a{:href => "new?start=#{start + 7.day}"} week
      = image_tag "arrow.gif"
    %td
      %a{:href => "new?start=#{start + 30.day}"} month
      = image_tag "arrow.gif"
  %table.book
    %thead
      %th
      - days.each do |day|
        %th
          ma 23.7
          /
            <haml:loud> day </haml:loud>
    %tbody
      - rooms.each do |room|
        %tr
          %td.book-room
            = room
          - days.each do |day|
            %th.book-cell
              = rawdiv(room,day)
              - if room_free(room,day)
                %a{:href => "#"}
                .ok
                  = image_tag "ok.png"  , :height => "18px" , :width => "18px"
              - else
                .not
                  = image_tag "not.png"  , :height => "18px" , :width => "18px"
                  .name
                    etunimi sukunimi
  %div
    #room Choose
    #arriving date

app/views/bookings/booking.html.haml
%h2
  = raw t('booking.header')
%strong
  = raw t('booking.booking1')
%br/
%br/
= raw t('booking.booking2')
%br/
%br/
%br/
%br/

.left
  =link_to "https://www.airbnb.com/rooms/50631940" do
    Rooms
    = image_tag "feenix.jpg"  , :width => "100%" , :alt => "allas"
.left
  =link_to "https://www.hubfeenix.fi/" do
    = image_tag "feenix_lintu.jpg"  , :width => "100%" , :alt => "garden"
    Info

app/views/bookings/confirm.html.haml
- if flash.notice
  .flash.notice= flash.notice
= raw t('booking.received')
%br
%br
%br= t("booking.name") + " : " + @booking.name
%br= t("booking.email") + " : " + @booking.email
%br= t("booking.phone") + " : " + @booking.phone
%br= t("booking.room")+ " : " + @booking.room.capitalize
%br= t("booking.arriving") + " : " + @booking.arriving.to_s
%br= t("booking.nights") + " : " + @booking.nights.to_s
%br= t("booking.comment") + " : " + @booking.comment

%br
%br/
= raw t('booking.confirmation')
%br/
%br/
= raw t('booking.pay')
%br/
%br/

app/views/bookings/edit.html.haml
%h1 Editing booking
= render 'form'
= link_to 'Show', @booking
|
= link_to 'Back', bookings_path

app/views/bookings/index.html.haml
%h1 Listing bookings
%table
  %tr
    %th Email
    %th Arriving
    %th Name
    %th Street
    %th Town
    %th Phone
    %th Leaving
    %th
    %th
    %th
  - @bookings.each do |booking|
    %tr
      %td= booking.email
      %td= booking.arriving
      %td= booking.name
      %td= booking.street
      %td= booking.town
      %td= booking.phone
      %td= booking.leaving
      %td= link_to 'Show', booking
      %td= link_to 'Edit', edit_booking_path(booking)
      %td= link_to 'Destroy', booking, :confirm => 'Are you sure?', :method => :delete
%br/
= link_to 'New Booking', new_booking_path

app/views/bookings/new.html.haml
= render 'form'

app/views/bookings/rooms_day.html.haml
- ["lootus","aurinko","safron","oranssi","vihrea","taivas","ruusu"].each do |room|
  - selected = params[:booking] ? params[:booking][:room] == room : false ;
  %td
    %div{:class => "free #{'selected' if selected}" , :room => room}
      %a{:href => "#"}
        = room.capitalize

app/views/bookings/show.html.haml
%p#notice= notice
%p
  %b Email:
  = @booking.email
%p
  %b Arriving:
  = @booking.arriving
%p
  %b Name:
  = @booking.name
%p
  %b Street:
  = @booking.street
%p
  %b Town:
  = @booking.town
%p
  %b Phone:
  = @booking.phone
%p
  %b Leaving:
  = @booking.leaving
= link_to 'Edit', edit_booking_path(@booking)
|
= link_to 'Back', bookings_path

app/views/layouts/application.html.haml
%html
  %head
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    %link{:href => "/favicon.ico", :rel => "shortcut icon", :type => "image/vnd.microsoft.icon"}/
    %meta{:content => "Bed and breakfast majoitus hotel Fiskars häät  Suite", :name => "keywords"}/
    %meta{:content => "Bed and Breakfast Villa Taika : #{t('slogan') + ' ' + t(@page + ".short")}", :name => "description"}/
    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "content-type"}/
    %meta{:content => @locale, "http-equiv" => "Content-Language"}/
    %title
      Bed &amp; Breakfast Villa Taika : #{t(@page + ".short")}
  %body
    #fb-root
    :javascript
      (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/fi_FI/sdk.js#xfbml=1&version=v2.0";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
    .main
      .header
        .centre
          %img{:alt => "Villa Taika logo", :src => "/images/logo_iso.png"}/
        .slogan= link_to t("booking.header") , "/#{@locale}/booking.html"
      .lcol
        .menu
          %ul
            - ["index" , "bed" ,"booking","groups","map","photos","activities"].each do |p|
              <li #{raw('class="active"') if params[:page] == p}>
              \#{link_to(t(p+'.short') , "/#{@locale}/#{p}.html")}
        .menuend
        .lcontent
          %h3.first
            %span= t "bed.rooms"
          %ul.divided
            %li= link_to  t("suites.short") , "/#{@locale}/suites.html"
            %li= link_to  t("deluxe.short") , "/#{@locale}/deluxe.html"
            %li= link_to  t("standard.short") , "/#{@locale}/standard.html"
          .divider
          - @locales.each do |lang|
            <a href="#{"/#{lang}/#{@page}.html"}" #{"class='selected'" if lang == @locale}>
            %img{:alt => lang.to_s, :src => "/images/#{lang.to_s}.gif"}/
          %h3
            %a{:href => "/#{@locale}/news.html"}
              %span= t("news.short")
          .news
            %a{:href => "/#{@locale}/news.html"}
              = t("news." + news.first + ".short")
      .rcol
        .rcontent
          = yield
        .divider
      .footer
        .kolmas
          %b> Villa Taika
          , Fiskarsintie 847, 10480 Antskog
          %br/
          www.villataika.fi&nbsp;&nbsp;&nbsp;info@villataika.fi
        .kolmas
          Raisa Kaipainen &amp; Torsten Rüger
        .kolmas
          %a{:href => "/#{@locale}/index.html"}
            %img{:alt => "", :border => "0", :height => "33", :src => "/images/logo_pien.gif", :width => "198"}/
    .divider
    %br/
    %br/
    %br/